### ISSUE TITLE
When and How are sessions closed?

### ISSUE THREAD

**Issue by loveabc** [quickfix-j/quickfixj#238]
Hi chrjohn,

I'm a new person using quick fix from China, and I have a question about create and close session.
In createSessions method of AbstractSocketAcceptor.java, you create a session using Session Factory, I think it's good, the Session implements Closeable interface, however, you don't put 'sessionFactory.create(sessionID, settings)' into try source, so I want to know When and how are sessions closed.
My app prints 'Too many open files' exception every second in QFJ Timer thread, so I wonder if it's because session isn't closed correctly.

Or where is there opening file operation in 'QFJ Timer' thead? sorry, I search but no result.

Looking forward to your reply & thanks
Tim

**Comment by chrjohn** [comment]
You don't state which OS you are on.  If on Linux please look here https://www.chrisnewland.com/javaioioexception-too-many-open-files-202
Please attach the result here. 
Thanks 
Chris

**Comment by loveabc** [comment]
Thanks for your reply.
Yes, my application runs on Linux.
The application just throws this exception sometimes, and I cannot reappear it,
so when I use 'lsof' to show 'open files' and it looks fine.
What you mean is use 'lsof' commander to find which process opens too many files, right?
In my view, since exception is printed in 'QFJ Timer' thread, it should quick process opens too many files.
Regards,
Tim

**Comment by chrjohn** [comment]
Of course the QFJ process. But it would be necessary to see which files exactly to find the cause. There is no stack trace? 
IIRC there was a problem where the file store was not closed under some circumstances. But the JIRA is currently down so I cannot check.

**Comment by chrjohn** [comment]
Also which QFJ version are you using?

**Comment by loveabc** [comment]
version is 1.6.4

**Comment by loveabc** [comment]
Hi, below is stack trace,


ERROR [QFJ Timer] o.a.m.c.s.SimpleloProcessorPool [SimpleloProcessorpooljava:219]
Failed to create a new instance of org.apache.mina.transport.socket.nio.NioProcessor:null
Java.lang.reflect.Invocation TargetException:null
at sun.reflect.GeneratedConstructorAccessor55.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorlmpl.newinstance(DelegatingConstructorAccessorlmpl.java:45)
at java.lang.reflect.Constructor.newlnstance(Constructor.java:423)
at org.apache.mina.core.service.SimpleloProcessorPool.<init>(SimpleloProcessorPool.java:198)
at org.apache.mina.core.service.SimpleloProcessorPool.<init>(SimpleloProcessorPool.java:115)
at
org.apache.mina.core.polling.AbstractPollingloConnector.<init>(AbstractPollingloConnector.java:97)
org.apache.mina.transport.socket.nio.NioSocketConnector.<init>(NioSocketConnector.java:56)
at quickfix.mina.ProtocolFactory.createloConnector(ProtocolFactory,.java:223)
at
quickfix.mina.initiator.loSessioninitiatorsConnectTask.setuploConnector(loSessionlnitiator.java:155)
at
quickfix.mina.initiator.losessioninitiators connectTask.resetloconnector(losessionlnitiator.java:335)
at quickfix.mina.initiator.loSessionlnitiator$ Connect Task.run(losessionlnitiator.java:195)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.,java:511)
at iava.util.concurrent.Future Task.runAndReset(FutureTask.java:308)
at
java.util.concurrent.Scheduled ThreadPoolExecutor$ScheduledFuture Task.access$301(ScheduledThread
PoolExecutor.java:180)
at
java.util.concurrent.Scheduled ThreadPoolExecutor$ScheduledFuture Task.run(ScheduledThreadPoolExec
utor.java:294)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.mina.core.RuntimeloException: Faled to opena selector.
at org apache.mina.transport.socket.nio.Nioprocessor.<init>(Nioprocessor.java:64)
..18 common frames omitted
Caused by: iava.io.IOException:Too many open files
at sun.nio.ch.lUtil.makePipe(Native Method)
at sun.nio.ch.EPollSelectorlmpl.<init>(EPollSelectorlmpl.java:65)
at sun.nio.ch.EPollSelectorProvider.openSelector(EPollSelectorProvider.java:36)
at java.nio.channels.Selector.open(Selector.java:227)
at org.apache.mina.transport.socket.nio.NioProcessor.<init>(NioProcessor.java:62)
..18 common frames omitted

**Comment by chrjohn** [comment]
Wow, that is quite old. Could you maybe try with a newer version?

**Comment by chrjohn** [comment]
I recall that there also were problems where connectors weren't closed properly on older versions.

**Comment by loveabc** [comment]
Thanks for your quick reply.
Your reply is very helpful for me.
Thanks again.

**Comment by loveabc** [comment]
This bug is fixed from which version?

**Comment by chrjohn** [comment]
I was referring to this pull request: #175 and #178 which are contained in QFJ 2.1.0.
There were also some updates to MINA (socket library used by QFJ) which could also improve things.

**Comment by chrjohn** [comment]
BTW, while you're at it, you might as well upgrade to 2.1.1 which has minor bug fixes as well (not around resource leaks but wouldn't hurt to upgrade anyway).

**Comment by loveabc** [comment]
Thanks, Let me try.

**Comment by chrjohn** [comment]
Please reopen if there are still open issues.
