### ISSUE TITLE
ConcurrentModificationException when stopping the Initiator

### ISSUE THREAD

**Issue by kurudj** [quickfix-j/quickfixj#403]
**Describe the bug**
When attempting to stop an initiator by calling a `initiator_.stop();` we get a ConcurrentModificationException that based on the stack trace is happening on the inside of the library. 

```
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.remove(HashMap.java:1507)
	at quickfix.mina.initiator.AbstractSocketInitiator.stopInitiators(AbstractSocketInitiator.java:320)
	at quickfix.SocketInitiator.stop(SocketInitiator.java:142)
	at quickfix.Connector.stop(Connector.java:45)
```

**To Reproduce**

It would be hard to reproduce since this callback is a part of a quite large codebase. The callback is made from a QuickFIXClient.java class from a close() method that attempts to close the connection.

**Expected behavior**

No exceptions.

**system information:**
 - OS: Linux
 - Java version: jdk-13
 - QFJ Version: 2.2.1

**Additional context**

**Comment by chrjohn** [comment]
Hi @kurudj ,

this has already been fixed as part of QFJ 2.3.0. Could you please try again with that version?

#324 

Thanks and cheers,
Chris.
