### ISSUE TITLE
Inexistant setUseClientMode method

### ISSUE THREAD

**Issue by pvenini** [quickfix-j/quickfixj#544]
When configuring application as acceptor using Quickfixj 2.3.1

Exception in thread "main" java.lang.NoSuchMethodError: 'void quickfix.mina.ssl.SSLFilter.setUseClientMode(boolean)'
	at quickfix.mina.acceptor.AbstractSocketAcceptor.installSSL(AbstractSocketAcceptor.java:136)
	at quickfix.mina.acceptor.AbstractSocketAcceptor.startAcceptingConnections(AbstractSocketAcceptor.java:109)
	at quickfix.SocketAcceptor.initialize(SocketAcceptor.java:110)
	at quickfix.SocketAcceptor.start(SocketAcceptor.java:103)

**To Reproduce**
SocketUseSSL=Y

**Expected behavior**
No error

**system information:**
 - OS: Windows 10
 - Java version JDK8
 - QFJ Version 2.3.1

**Comment by chrjohn** [comment]
QFJ extends SslFilter from mina and the method is there:

https://github.com/apache/mina/blob/35aafff17ee3fc655844058b28489c4c14af65fa/mina-core/src/main/java/org/apache/mina/filter/ssl/SslFilter.java#L349

Could it be that a newer version of mina is in your class path, maybe 2.2.0 or 2.2.1?

**Comment by pvenini** [comment]
You are right, we had mina-core 2.2.1 in the classpath. 
Sorry, I didn't realize the class was extending Mina.
